package io.rainett.bot.telegram.botactioncontainer.enumerations;

public enum UpdateType {

    CHAT_JOIN_REQUEST, CHAT_MEMBER, MY_CHAT_MEMBER,
    POLL_ANSWER, POLL, PRE_CHECKOUT_QUERY, SHIPPING_QUERY,
    CALLBACK_QUERY, CHOSEN_INLINE_QUERY, INLINE_QUERY,
    EDITED_CHANNEL_POST, CHANNEL_POST, EDITED_MESSAGE, MESSAGE

}
